version: "3.9"
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:14.1
    volumes:
      - postgres_data:/docker/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 1234:5432
    environment:
      POSTGRES_PASSWORD: "postgres"

volumes:
  postgres_data:
